master:
  adminUser: admin
  adminPassword: '123'
agent:
  image: adriagalin/jenkins-jnlp-slave
  tag: 1.4
  alwaysPullImage: true
  volumes:
   - type: HostPath
     volumeName: docker-sock
     hostPath: /var/run/docker.sock
     mountPath: /var/run/docker.sock